# rotulos , titulos e mensagens
status=Status
pesquisando=... Pesquisando
carregando=... Carregando
mensagem=Mensagem
menu=Menu
sair=Sair
voltar=Voltar
fechar=Fechar
cancelar=Limpar
cadastrar=Cadastrar
localizar=Localizar
selecione=Selecione opção:
selecionar=Selecionar
selecionarTema=Selecionar Tema:
selecionePessoa=Selecione Pessoa:
tipoPessoa=Tipo Pessoa
cliente=Cliente
titulo=Título
titulo_area=Acesso do Usuário
usuario=Usuário
gerente=Gerente
senha=Senha
enviar=Enviar
enviado=Enviado
enviadoJa=Já enviado(s)?
nenhum=Nenhum
excluir=Excluir
editar=Editar
inicio=Início
aditivo=Aditivo
aditivos=Aditivos
cpf_cnpj_sacado=CPF/CNPJ do Sacado
cpf_cnpj=CPF/CNPJ
contratosMae=Contratos Mãe
documento=Documento
documentos=Documentos
documentosAbertos=Documentos - Abertos
documentosEntradas=Documentos - Entradas
documentosLiquidados=Documentos - Liquidados
documentosBoletos=2� Via de Boleto
numero=N�mero
numeroAditivo=N�mero Aditivo
numeroDoc=N�mero Doc.
periodo=Per�odo
pessoa=Pessoa
pessoas=Pessoas
a=a
cedente=Cedente
cpf=CPF
cnpj=CNPJ
pesquisar=Pesquisar
imprimirRelatorio=Imprimir Relat�rio
imprimirBoleto=Boleto
exportarArquivo=Exportar Arquivo
data=Data
valor=Valor
valorAmortizado=Valor Amortizado
valorEmAberto=Valor Em Aberto
valorQuitado=Valor Quitado
amortizacao=Amortiza��o
amortizado=Amortizado
encargo=Encargo
acrescimo=Acr�scimo
desconto=Desconto
desembolso=Desembolso
ordenar=Ordenar
operacao=Opera��o
operacoes=Opera��es
tipo=Tipo
tipos=Tipos
tipoLiquidacao=Tipo Liquida��o
vencimento=Vencimento
vencimentos=Vencimentos
confirmacao=Confirma��o
numeroBancario=N� Banc�rio
vencimentoOriginal=Vcto. Original
prorrogadoPara=Prorrogado Para
entrada=Entrada
entradas=Entradas
saldo=Saldo
saldoEmAberto=Saldo em Aberto
totalSaldoEmAberto=Total Saldo em Aberto
totalEmAberto=Total em Aberto
totalDocumentosEmAberto=Total de Documentos em Aberto
totalQuitado=Total Liquidado
ultimaLiquidacao=�ltima Liquida��o
nomeSacado=Nome do Sacado
cidade_estado_sacado=Cidade/Estado do Sacado
banco=Banco
agencia=Ag�ncia
envioBanco=Envio ao Banco
tipoCobranca=Tipo de Cobran�a
cobranca=Cobran�a
titulos=T�tulos
cheque=Cheque
cheques=Cheques
total=Total
valorTotal=Valor Total
desembolsoTotal=Desembolso
totalAditivos=Total de Aditivos
visualizar=Visualizar
visualizarDetalhes=Visualizar Detalhes
dataEnvio=Data de Envio
dataEmissao=Data de Emiss�o
dataHoraEnvio=Data/Hora de Envio
dataHora=Data/Hora
dataVencimento=Data de Vencimento
dataLancamento=Data de Lan�amento
dataProrrogacao=Data Prorroga��o
emissao=Emiss�o
sacado=Sacado
localCobranca=Local de Cobran�a
detalhes=Detalhes
boleto=Boleto
segundaVia=2�Via
segundaViaBoleto=2�Via Boleto
barra=/
nome=Nome
nomes=Nomes
quantidade=Quantidade
enviados=Enviados
enviarDocumentos=Envio de Documentos
enviarCheques=Envio de Cheques
documentosEnviados=Documentos Enviados
inserirDocumentos=Digita��o de Documentos
inserirTitulos=Inserir T�tulos
inserirTitulo=Inserir T�tulo
editarTitulo=Editar T�tulo
inserirCheques=Inserir Cheques
inserirCheque=Inserir Cheque
editarCheque=Editar Cheque
inserirSacado=Inserir Sacado
inserirPessoa=Inserir Pessoa
inserirDoc=Inserir Documento
inserirDocs=Inserir Documentos
digitacaoTitulos=Digita��o de T�tulos
digitacaoCheques=Digita��o de Cheques
digitacaoSacados=Digita��o de Sacados
fisica=F�sica
juridica=Jur�dica
cadastrarSacado=Cadastrar Sacado
cadastrarTitulo=Cadastrar T�tulo
cadastrarCheque=Cadastrar Cheque
salvarSacado=Salvar Sacado
salvarTitulo=Salvar T�tulo
salvarCheque=Salvar Cheque
codigo=C�digo
endereco=Endere�o
residencial=Residencial
comercial=Comercial
enderecoResidencial=Endere�o Residencial
enderecoComercial=Endere�o Comercial
enderecoCobranca=Endere�o Cobran�a
enderecoEmail=Endere�o E-mail
cep=CEP
cidade=Cidade
estado=Estado
bairro=Bairro
telefone=Fone
fax=FAX
buscar=Buscar
ambos=Ambos
naoEnviar=N�o Enviar
site=Site
todos=Todos
periodoInicio=Per�odo Inicial
periodoFim=Per�odo Final
periodoVencimentoInicio=Per�odo Vencimento Inicial
periodoVencimentoFim=Per�odo Vencimento Final
asterisco=*
piclas='
resumo=Resumo
inserir=Inserir
abertas=Abertas
abertos=Abertos
liquidadas=Liquidadas
liquidados=Liquidados
liquidacoes=Liquida��es
emAberto=Em Aberto
localizarAditivos=Localizar Aditivos
localizarBoleto=2� Via de Boleto
localizarPorNumero=Localizar por N�mero
localizarLiquidacoes=Localizar Liquida��es
localizarAEnviar=Localizar a Enviar
localizarEnviados=Localizar Enviados
localizarTitulos=T�tulos a Enviar
localizarCheques=Cheques a Enviar
imprimirTermo=Imprimir termo
theme=Tema
empresa=Empresa
licensaNum=Licensa N\u00BA 
buscarEndereco=Buscar Endere�o
parcial=Parcial
abatimento=Abatimento
forma=Forma
recebimento=Recebimento
numeroCMC7=N�CMC7
gerarArquivoTxt=Gerar Arquivo
enviarArquivoTxt=Enviar Arquivo
prorrogacao=Prorroga��o
prorrogacoes=Prorroga��es
prorrogacoesEmAberto=Prorroga��es em Aberto
localizarProrrogacoes=Localizar Prorroga��es
tarifa=Tarifa
tarifas=Tarifas
tarifasProrrogacoes=Tarifas/Prorroga��es
tarifasEmAberto=Tarifas em aberto
tarifasProrrogacoesEmAberto=Tarifas e prorroga��es em aberto
tarifasProrrogacoesAberto=Tarifas e prorroga��es abertas
tarifasProrrogacoesLiquidado=Tarifas e prorroga��es liquidadas
tarifasLiquidado=Tarifas liquidadas
prorrogacoesLiquidado=Prorroga��es liquidadas
localizarTarifas=Localizar Tarifas
descricao=Descri��o
pessoaFisica=Pessoa F�sica
pessoaJuridica=Pessoa Jur�dica
sim=Sim
nao=N�o
retornar=Retornar
filtrar=Filtrar
entreSenha=entre com sua senha
fraca=fraca
normal=normal
forte=forte
grafico=Gr�fico de Documentos em Aberto
escolha=Escolha

# titulos
copyright=Courier System Online - Copyright� 2023 - Todos os direitos reservados.
visualizacao=Melhor visualizado em 1024x768
aplicacao=CSOnline
sessaoFinalizada=Sess�o Finalizada!
paginaNaoEncontrada=P�gina N�o Encontrada!
resumoTitulos=Resumo de T�tulos
resumoDocumentos=Resumo de Documentos
tituloAtraso=Documentos em Atraso
tituloAberto=Documentos a Vencer
tituloLiquidado=Documentos Liquidados no Dia
contratoMae=Contratos M�e
aguarde=Aguarde...
processando=Sistema em processamento
cadastro=Cadastro
cadastros=Cadastros
localizarDocumentos=Localizar Documentos
enviarTitulos=Enviar T�tulos
selecionarDocumentos=Selecionar t�tulos
selecionarCheques=Selecionar cheques

# subtitulos
dataSistema=Data do Sistema:
pesquisaAditivos=Pesquisa pelo seus aditivos
pesquisaBoletos=Pesquisa pelos seus t�tulos
pesquisaCheques=Pesquisa pelos seus t�tulos e cheques
pesquisaLiquidacoes=Pesquisa pelas suas liquida��es
pesquisaProrrogacoes=Pesquisa pelas suas prorroga��es abertas
pesquisaTarifas=Pesquisa por suas tarifas em aberto
pesquisaTarifasProrrogacoes=Pesquisa tarifas e prorroga��es abertas
pesquisaTarifasProrrogacoesLiquidados=Pesquisa tarifas e prorroga��es liquidadas
pesquisaTarifasLiquidados=Pesquisa pelas suas tarifas liquidadas
pesquisaProrrogacoesLiquidados=Pesquisa pelas suas prorroga��es liquidadas
resumoAteData=Resumo at� a data do sistema
inserirTituloCheques=Inserir T�tulos e Cheques
enviarEndereco=Endere�o para enviar correspond�ncia
pesquisaMae=Pesquisa pelos seus contratos m�e
cumprimento=Seja Bem Vindo!
resumoAtualizado=Resumo Atualizado
sairSaqueNET=Sair do CSOnline
escolherTheme=Escolha um tema para o sistema

# mensagem padrao
mensagem_01=N�o foram encontrados resultados.
mensagem_02=Imprimir Termo
mensagem_03=Para retornar, clique aqui!
mensagem_04=Visualizar detalhes.
mensagem_05=Tempo finalizado de sess�o, para retornar, clique aqui!
mensagem_06=P�gina N�o Encontrada!

#mensagem validacao
cpf_obrigatorio=Informe CPF!
cnpj_obrigatorio=Informe CNPJ!
data_vencimento_obrigatorio=Informe Data de Vencimento!
data_emissao_obrigatorio=Informe Data de Emiss�o!
titulo_obrigatorio=Informe T�tulo!
valor_obrigatorio=Informe Valor!
cmc7_mensagem=*Campo n�o obrigat�rio!
validacaoUsuario=Usu�rio inv�lido!
obrigatorioUsuario=Digite usu�rio!
validacaoSenha=Senha inv�lida!
obrigatorioSenha=Digite senha!

#menu page
administrator=Administrador
administrators=Administradores
users=Usu�rios
business=Neg�cio
businesses=Neg�cios
customer=Cliente
customers=Clientes
courier=Entregador
couriers=Entregadores
delivery=Entraga
deliveries=Entregas
listAll=Listar todos
add=Incluir
login=Logar
edit=Editar
view=Visualizar
save=Salvar
cancel=Cancelar
delete=Deletar
listCompleted=Listar Completas
listNotCompleted=Listar Em Aberto
exit=Sair
timeSystem=Data do Sistema
no_items_registered=Nenhum item registrado

#user/users pages
id=ID
user=Usu�rio
role=Perfil
name=Nome Completo
login=Login
email=E-mail
email2=E-mail Alternativo
address=Endere�o Completo
mobile=N�mero de Celular

#business/businesses pages
password=Senha
repeat=Repita Senha

#customer/customers pages
factor_customer=Fator
price_table=Tabela de Pre�o
price_tables=Tabela de Pre�os

#courier/couriers pages
factor_courier=Fator
update_password=Atualizar Senha

#change_password
newPassword=Nova senha
newRepeat=Repita nova senha
change_password=Mudar senha
admin=Administrar

#delivery/delivery_cu/delivery_co deliveries pages
datetime=Data/Hora
start=Partida de
destination=Destino
contact=Contato
description=Descri��o
volume=Volume
weight=Peso
km=Km
additional=Custo Adicional
cost=Custo
completed=Completo
received=Em Aberto
send=Enviar Email
yes=Sim
non=N�o
composeSms=Compor SMS
sms=SMS
sendSms=Enviar SMS
viewSms=Ver SMS
editSms=Editar SMS

#pricetable pages
price=Pre�o
vehicle=Ve�culo
table=Tabela
tables=Tabelas
local=Destino

#messages page
os=Ordem de Servi�o
message=Mensagem
messages=Mensagens
sms_messages=Mensagens
mobile_from=Celular
type=Tipo
what_os=Qual OS?
sms_sent=Enviado
sms_received=Recebido